const data = [
  {
    adult: false,
    backdrop_path: "/jvRewPpawHAfBW38EzHoFdTVEez.jpg",
    genre_ids: [16, 28, 12, 80, 14],
    id: 732450,
    original_language: "en",
    original_title: "Batman: Soul of the Dragon",
    overview:
      "Bruce Wayne faces a deadly menace from his past, with the help of three former classmates: world-renowned martial artists Richard Dragon, Ben Turner and Lady Shiva.",
    popularity: 587.254,
    poster_path: "/uDhnTtSxU5a8DtZdbbin3aZmkmU.jpg",
    release_date: "2021-01-12",
    title: "Batman: Soul of the Dragon",
    video: false,
    vote_average: 7.2,
    vote_count: 76,
  },
  {
    adult: false,
    backdrop_path: "/kU7ZiyeUwcpTkYj3UcxSqGdZmxY.jpg",
    genre_ids: [16, 28],
    id: 618353,
    original_language: "en",
    original_title: "Batman: Death in the Family",
    overview:
      "Tragedy strikes the Batman's life again when Robin Jason Todd tracks down his birth mother only to run afoul of the Joker. An adaptation of the 1988 comic book storyline of the same name.",
    popularity: 255.278,
    poster_path: "/k8Q9ulyRE8fkvZMkAM9LPYMKctb.jpg",
    release_date: "2020-10-13",
    title: "Batman: Death in the Family",
    video: false,
    vote_average: 7.3,
    vote_count: 165,
  },
  {
    adult: false,
    backdrop_path: "/2va32apQP97gvUxaMnL5wYt4CRB.jpg",
    genre_ids: [14, 28],
    id: 268,
    original_language: "en",
    original_title: "Batman",
    overview:
      'Batman must face his most ruthless nemesis when a deformed madman calling himself "The Joker" seizes control of Gotham\'s criminal underworld.',
    popularity: 37.398,
    poster_path: "/tDexQyu6FWltcd0VhEDK7uib42f.jpg",
    release_date: "1989-06-23",
    title: "Batman",
    video: false,
    vote_average: 7.2,
    vote_count: 5294,
  },
  {
    adult: false,
    backdrop_path: "/lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg",
    genre_ids: [28, 80, 18],
    id: 272,
    original_language: "en",
    original_title: "Batman Begins",
    overview:
      "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
    popularity: 54.3,
    poster_path: "/1P3ZyEq02wcTMd3iE4ebtLvncvH.jpg",
    release_date: "2005-06-10",
    title: "Batman Begins",
    video: false,
    vote_average: 7.7,
    vote_count: 15634,
  },
  {
    adult: false,
    backdrop_path: "/3eKBHl5pYrXDd26Mc8zYxG8CHex.jpg",
    genre_ids: [878, 28, 14],
    id: 415,
    original_language: "en",
    original_title: "Batman & Robin",
    overview:
      "Batman and Robin deal with relationship issues while preventing Mr. Freeze and Poison Ivy from attacking Gotham City.",
    popularity: 28.289,
    poster_path: "/bsg0mrxUKyJoL4oSGP5mlhEsqp.jpg",
    release_date: "1997-06-20",
    title: "Batman & Robin",
    video: false,
    vote_average: 4.3,
    vote_count: 3552,
  },
  {
    adult: false,
    backdrop_path: "/moYfd709S8xnb8Od2yeG5VBt9Bp.jpg",
    genre_ids: [28, 14],
    id: 364,
    original_language: "en",
    original_title: "Batman Returns",
    overview:
      "While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman.",
    popularity: 32.696,
    poster_path: "/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg",
    release_date: "1992-06-19",
    title: "Batman Returns",
    video: false,
    vote_average: 6.8,
    vote_count: 4415,
  },
  {
    adult: false,
    backdrop_path: "/jZfpDaku8fm14GZNc8lr7Li88Rm.jpg",
    genre_ids: [28, 80, 18],
    id: 414906,
    original_language: "en",
    original_title: "The Batman",
    overview: "Plot unknown.",
    popularity: 35.426,
    poster_path: "/yYMG2uT87auGztI9aKVzBB2pHvK.jpg",
    release_date: "2022-03-03",
    title: "The Batman",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/eevJuYAitUe6VwFN29aFwzeyeTr.jpg",
    genre_ids: [80, 16, 9648, 28],
    id: 537056,
    original_language: "en",
    original_title: "Batman: Hush",
    overview:
      "A mysterious new villain known only as Hush uses a gallery of villains to destroy Batman's crime-fighting career as well as Bruce Wayne's personal life, which has been further complicated by a  relationship with Selina Kyle/Catwoman.",
    popularity: 26.99,
    poster_path: "/eiVQORVyVuNNZHPAELuWtlXoQsD.jpg",
    release_date: "2019-07-19",
    title: "Batman: Hush",
    video: false,
    vote_average: 7.3,
    vote_count: 475,
  },
  {
    adult: false,
    backdrop_path: "/snlu32RmjldF9b068UURJg8sQtn.jpg",
    genre_ids: [28, 80, 14],
    id: 414,
    original_language: "en",
    original_title: "Batman Forever",
    overview:
      "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat.",
    popularity: 26.686,
    poster_path: "/k6EQ2OewzjF8TcPgok9wxpPAgXW.jpg",
    release_date: "1995-06-16",
    title: "Batman Forever",
    video: false,
    vote_average: 5.4,
    vote_count: 3672,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 148918,
    original_language: "ro",
    original_title: "Superman, Spiderman sau Batman",
    overview:
      "Aron, a 5-year-old boy, sets together with his worried father on a journey at the end of which he wishes, like the superheroes in the comic books, to save his mother suffering from a heart condition.",
    popularity: 38.629,
    poster_path: "/iUp85s5s7eaPbuCUNqOCeJCEVpY.jpg",
    release_date: "2011-06-01",
    title: "Superman, Spiderman or Batman",
    video: false,
    vote_average: 7,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: "/gwXMBVAsLvNcZuzWDEswexdqNLa.jpg",
    genre_ids: [10751, 12, 35, 878, 80],
    id: 2661,
    original_language: "en",
    original_title: "Batman",
    overview:
      "The Dynamic Duo faces four super-villains who plan to hold the world for ransom with the help of a secret invention that instantly dehydrates people.",
    popularity: 17.003,
    poster_path: "/iLC5bgc1NOuXpfBxtb8xEj6tzvu.jpg",
    release_date: "1966-07-30",
    title: "Batman",
    video: false,
    vote_average: 6.3,
    vote_count: 534,
  },
  {
    adult: false,
    backdrop_path: "/g2XhZJhFiHcczWcXEEldItG53gd.jpg",
    genre_ids: [28, 12, 16],
    id: 321528,
    original_language: "en",
    original_title: "Batman vs. Robin",
    overview:
      'Damian Wayne is having a hard time coping with his father\'s "no killing" rule. Meanwhile, Gotham is going through hell with threats such as the insane Dollmaker, and the secretive Court of Owls.',
    popularity: 24.98,
    poster_path: "/aGp9XDXmVM5lCKHWtgBC15S7XLr.jpg",
    release_date: "2015-04-14",
    title: "Batman vs. Robin",
    video: false,
    vote_average: 7.2,
    vote_count: 573,
  },
  {
    adult: false,
    backdrop_path: "/2GIA8FKNxI69RnytQquoDbrAJ7L.jpg",
    genre_ids: [16, 28, 12, 10751],
    id: 22855,
    original_language: "en",
    original_title: "Superman/Batman: Public Enemies",
    overview:
      "United States President Lex Luthor uses the oncoming trajectory of a Kryptonite meteor to frame Superman and declare a $1 billion bounty on the heads of the Man of Steel and his ‘partner in crime’, Batman. Heroes and villains alike launch a relentless pursuit of Superman and Batman, who must unite—and recruit help—to try and stave off the action-packed onslaught, stop the meteor Luthors plot.",
    popularity: 54.647,
    poster_path: "/izvMc22ywSLFWUXZEIuJJ8dms75.jpg",
    release_date: "2009-09-29",
    title: "Superman/Batman: Public Enemies",
    video: false,
    vote_average: 6.9,
    vote_count: 390,
  },
  {
    adult: false,
    backdrop_path: "/2JVnUtyUKbQm165cXUF9r5iVPDo.jpg",
    genre_ids: [12, 28, 16, 878],
    id: 408648,
    original_language: "en",
    original_title: "Batman and Harley Quinn",
    overview:
      "Batman and Nightwing are forced to team with the Joker's sometimes-girlfriend Harley Quinn to stop a global threat brought about by Poison Ivy and Jason Woodrue, the Floronic Man.",
    popularity: 24.413,
    poster_path: "/zrqIPpbqCgrs1rS0ltxNicJcuse.jpg",
    release_date: "2017-08-14",
    title: "Batman and Harley Quinn",
    video: false,
    vote_average: 6.1,
    vote_count: 412,
  },
  {
    adult: false,
    backdrop_path: "/doiUtOHzcxXFl0GVQ2n8Ay6Pirx.jpg",
    genre_ids: [28, 12, 14],
    id: 209112,
    original_language: "en",
    original_title: "Batman v Superman: Dawn of Justice",
    overview:
      "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
    popularity: 75.921,
    poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
    release_date: "2016-03-23",
    title: "Batman v Superman: Dawn of Justice",
    video: false,
    vote_average: 5.9,
    vote_count: 14256,
  },
  {
    adult: false,
    backdrop_path: "/jLslJietfQJEgOvQHk4fRYFCnTS.jpg",
    genre_ids: [28, 16, 878],
    id: 366924,
    original_language: "en",
    original_title: "Batman: Bad Blood",
    overview:
      "Bruce Wayne is missing. Alfred covers for him while Nightwing and Robin patrol Gotham City in his stead and a new player, Batwoman, investigates Batman's disappearance.",
    popularity: 25.166,
    poster_path: "/1UmPJWfaivtNjsScJqcsbsQRGNY.jpg",
    release_date: "2016-03-22",
    title: "Batman: Bad Blood",
    video: false,
    vote_average: 7.1,
    vote_count: 508,
  },
  {
    adult: false,
    backdrop_path: "/jqnbac3oind5VOcAN0mTXyapOGh.jpg",
    genre_ids: [10751, 28, 16, 35, 14],
    id: 324849,
    original_language: "en",
    original_title: "The Lego Batman Movie",
    overview:
      "A cooler-than-ever Bruce Wayne must deal with the usual suspects as they plan to rule Gotham City, while discovering that he has accidentally adopted a teenage orphan who wishes to become his sidekick.",
    popularity: 30.987,
    poster_path: "/snGwr2gag4Fcgx2OGmH9otl6ofW.jpg",
    release_date: "2017-02-08",
    title: "The Lego Batman Movie",
    video: false,
    vote_average: 7.2,
    vote_count: 3615,
  },
  {
    adult: false,
    backdrop_path: "/3YHWdGyiuLVE2x4s3v3C35ZhFyl.jpg",
    genre_ids: [10751, 16, 35, 9648],
    id: 287757,
    original_language: "en",
    original_title: "Scooby-Doo Meets Batman",
    overview:
      'Scooby-Doo Meets Batman is a video compilation from Warner Bros. Home Entertainment. It consists of two episodes from Hanna-Barbera\'s The New Scooby-Doo Movies, "The Dynamic Scooby Doo Affair" and "The Caped Crusader Caper", where Scooby-Doo and the gang team up with Batman and Robin to capture Joker and the Penguin.',
    popularity: 19.408,
    poster_path: "/uI9enNoQsqseLXQK60YbscDr5L6.jpg",
    release_date: "1972-06-14",
    title: "Scooby-Doo Meets Batman",
    video: true,
    vote_average: 7.1,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/rSjFHjE4cCO1eCQ3VN7VRu6ZYqh.jpg",
    genre_ids: [16, 28, 12],
    id: 251519,
    original_language: "en",
    original_title: "Son of Batman",
    overview:
      "Batman learns that he has a violent, unruly pre-teen son with Talia al Ghul named Damian Wayne who is secretly being raised by Ra's al Ghul and the League of Assassins. When Ra's al Ghul apparently dies after a battle with Deathstroke, Batman must work to stop his long-lost son from taking revenge and guiding him to a righteous path, in addition to the chance for the pair to truly acknowledging each other as family.",
    popularity: 20.919,
    poster_path: "/yHx8OLSKc3VtIBB5lIe90c0fHOX.jpg",
    release_date: "2014-05-13",
    title: "Son of Batman",
    video: false,
    vote_average: 7,
    vote_count: 672,
  },
  {
    adult: false,
    backdrop_path: "/wNyhtxSazhYVSG1So8zgGTqVFVo.jpg",
    genre_ids: [28, 16, 80, 18],
    id: 382322,
    original_language: "en",
    original_title: "Batman: The Killing Joke",
    overview:
      "As Batman hunts for the escaped Joker, the Clown Prince of Crime attacks the Gordon family to prove a diabolical point mirroring his own fall into madness.",
    popularity: 31.852,
    poster_path: "/nxncAAL1FUKtQWs4uhs5jf1MVut.jpg",
    release_date: "2016-07-24",
    title: "Batman: The Killing Joke",
    video: false,
    vote_average: 6.6,
    vote_count: 1237,
  },
];

export default data;
