const data = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/lYGrME7aLWkzKB5h0FLNjjHKWLY.jpg",
        genre_ids: [878, 18, 10749],
        vote_count: 2,
        original_language: "en",
        original_title: "Bliss",
        poster_path: "/b7BllsQkD6nTkAdtd28UVCmKqVi.jpg",
        id: 613911,
        video: false,
        vote_average: 6.5,
        title: "Bliss",
        overview:
          "A mind-bending love story following Greg who, after recently being divorced and then fired, meets the mysterious Isabel, a woman living on the streets and convinced that the polluted, broken world around them is just a computer simulation. Doubtful at first, Greg eventually discovers there may be some truth to Isabel’s wild conspiracy.",
        release_date: "2021-02-05",
        popularity: 42.773,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/7ciRlInNzc4JSdMj2adwmgxHRna.jpg",
        genre_ids: [28, 12, 18, 14, 878],
        id: 581389,
        original_language: "ko",
        original_title: "승리호",
        overview:
          "In the year 2092, space is full of dangerous floating garbage like discarded satellites and deserted spaceships. The crew of a space junk collector ship called The Victory discovers a humanoid robot that’s known to be a weapon of mass destruction. They get involved in a risky business deal and travel through space looking for garbage they can make money off of while also competing with rival junk collectors.",
        poster_path: "/hO3pz1wHkFveyfFQx8O5Yz8ErsK.jpg",
        release_date: "2021-02-05",
        title: "Space Sweepers",
        video: false,
        vote_average: 0,
        vote_count: 0,
        popularity: 37.911,
        media_type: "movie",
      },
      {
        genre_ids: [10765, 9648, 35, 18],
        original_language: "en",
        poster_path: "/glKDfE6btIRcVB5zrjspRIs4r52.jpg",
        first_air_date: "2021-01-15",
        vote_average: 8.4,
        original_name: "WandaVision",
        origin_country: ["US"],
        id: 85271,
        vote_count: 3294,
        overview:
          "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
        backdrop_path: "/57vVjteucIF3bGnZj6PmaoJRScw.jpg",
        name: "WandaVision",
        popularity: 2798.473,
        media_type: "tv",
      },
      {
        genre_ids: [18, 10749],
        original_language: "en",
        original_title: "Malcolm & Marie",
        poster_path: "/bdidDnAZwchN5vTenoNuhGPJTri.jpg",
        video: false,
        vote_average: 6.8,
        overview:
          "A filmmaker and his girlfriend return home from his movie premiere, smoldering tensions and painful revelations push them toward a romantic reckoning.",
        release_date: "2021-01-28",
        vote_count: 4,
        title: "Malcolm & Marie",
        adult: false,
        backdrop_path: "/5LCz61vWbYNjEVxxhO2ZLniOkgU.jpg",
        id: 722913,
        popularity: 18.43,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg",
        genre_ids: [53, 80],
        vote_count: 157,
        original_language: "en",
        original_title: "The Little Things",
        poster_path: "/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg",
        id: 602269,
        video: false,
        vote_average: 6.4,
        title: "The Little Things",
        overview:
          "Deputy Sheriff Joe \"Deke\" Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who's terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke's past, uncovering disturbing secrets that could threaten more than his case.",
        release_date: "2021-01-27",
        popularity: 879.985,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/cGJUnIquDE7SZpCS7YDG29roLwL.jpg",
        genre_ids: [35, 18, 53],
        id: 780154,
        original_language: "pl",
        original_title: "Wszyscy moi przyjaciele nie żyją",
        overview:
          "A group of friends at a New Year’s Eve party go through a whirlwind of events that exposes secrets, breaks hearts — and leads to a shocking outcome.",
        poster_path: "/4GGF9oW3b8qqjvig3n8Qftl4P1Q.jpg",
        release_date: "2020-12-28",
        title: "All My Friends Are Dead",
        video: false,
        vote_average: 5.4,
        vote_count: 46,
        popularity: 11.266,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/bblKpucB0XbyQBmfXsaRN985Rgh.jpg",
        genre_ids: [18],
        original_language: "en",
        original_title: "Palmer",
        poster_path: "/xSDdRAjxKAGi8fUBLOqSrBhJmF0.jpg",
        video: false,
        vote_average: 8.3,
        vote_count: 121,
        overview:
          "After 12 years in prison, former high school football star Eddie Palmer returns home to put his life back together—and forms an unlikely bond with Sam, an outcast boy from a troubled home. But Eddie's past threatens to ruin his new life and family.",
        release_date: "2021-01-29",
        title: "Palmer",
        id: 458220,
        popularity: 410.752,
        media_type: "movie",
      },
      {
        backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
        genre_ids: [14, 28, 12],
        original_language: "en",
        original_title: "Wonder Woman 1984",
        poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
        title: "Wonder Woman 1984",
        vote_average: 7,
        vote_count: 3324,
        overview:
          "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
        release_date: "2020-12-16",
        video: false,
        id: 464052,
        adult: false,
        popularity: 2638.702,
        media_type: "movie",
      },
      {
        genre_ids: [18, 9648],
        original_language: "pt",
        poster_path: "/hh4uZv4lVkTBsBqtHCA5B4EMHBR.jpg",
        vote_average: 0,
        vote_count: 0,
        overview:
          "An environmental police officer uncovers a hidden world of mythological entities from Brazilian folklore when he finds a connection between the mysterious appearance of a dead river dolphin on a Rio de Janeiro beach and the death of his beloved wife.",
        backdrop_path: "/lXzu1IZmzDulGeqqrknoE7c5hak.jpg",
        first_air_date: "2021-02-05",
        original_name: "Cidade Invisível",
        origin_country: ["BR"],
        id: 110529,
        name: "Invisible City",
        popularity: 32.505,
        media_type: "tv",
      },
      {
        backdrop_path: "/l6a9odrGrkd9a26ja8pWJgHG44I.jpg",
        first_air_date: "2021-02-03",
        genre_ids: [18],
        id: 87049,
        name: "Firefly Lane",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Firefly Lane",
        overview:
          "For decades, childhood best friends Kate and Tully have weathered life's storms together -- until a betrayal threatens to break them apart for good.",
        poster_path: "/vJdhhyideVVOw9nT9kaD4yKD53z.jpg",
        vote_average: 7.8,
        vote_count: 6,
        popularity: 52.679,
        media_type: "tv",
      },
      {
        backdrop_path: "/gmP41e2bJcFjTzCQFmMoSvfNbxB.jpg",
        genre_ids: [18, 36],
        original_language: "en",
        original_title: "The Dig",
        poster_path: "/dFDNb9Gk1kyLRcconpj7Mc7C7IL.jpg",
        title: "The Dig",
        vote_average: 7.1,
        vote_count: 182,
        overview:
          "As WWII looms, a wealthy widow hires an amateur archaeologist to excavate the burial mounds on her estate. When they make a historic discovery, the echoes of Britain's past resonate in the face of its uncertain future‎.",
        release_date: "2021-01-14",
        video: false,
        id: 532865,
        adult: false,
        popularity: 126.4,
        media_type: "movie",
      },
      {
        overview:
          "In 1950s Italy, a farmer's dream of improving workers’ living conditions collapses when he falls for a landowner's daughter. Based on true events.",
        release_date: "2021-02-05",
        adult: false,
        backdrop_path: "/fNGrKqYTroEBAeUZl6m4vdQLqj.jpg",
        title: "The Last Paradiso",
        genre_ids: [18, 10749],
        original_language: "it",
        original_title: "L'ultimo paradiso",
        poster_path: "/blB1T2zUAqP9Qv8dyoB9Xn7W7qI.jpg",
        vote_count: 0,
        video: false,
        id: 746422,
        vote_average: 0,
        popularity: 25.788,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg",
        genre_ids: [28, 80, 53],
        original_language: "es",
        original_title: "Bajocero",
        poster_path: "/dWSnsAGTfc8U27bWsy2RfwZs0Bs.jpg",
        video: false,
        vote_average: 6.6,
        vote_count: 166,
        overview:
          "When a prisoner transfer van is attacked, the cop in charge must fight those inside and outside while dealing with a silent foe: the icy temperatures.",
        release_date: "2021-01-29",
        title: "Below Zero",
        id: 587996,
        popularity: 456.642,
        media_type: "movie",
      },
      {
        backdrop_path: "/q4JREf8dYSlZesQZ6LJNqpudaDm.jpg",
        genre_ids: [28, 12, 18, 14, 53],
        original_language: "es",
        original_title: "Black Beach",
        poster_path: "/bG11vZALd21wrnusUygZ8M28LcU.jpg",
        title: "Black Beach",
        vote_average: 6.3,
        vote_count: 3,
        overview:
          "Carlos is a businessman who gets a request to intercede on behalf a US engineer in the oil industry who's been kidnapped.",
        release_date: "2020-09-25",
        video: false,
        id: 735129,
        adult: false,
        popularity: 20.902,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Saint Maud",
        poster_path: "/uQjxpEYktu36ZiWKfn0t0FySmXl.jpg",
        video: false,
        vote_average: 6.8,
        overview:
          "Having recently found God, self-effacing young nurse Maud arrives at a plush home to care for Amanda, a hedonistic dancer left frail from a chronic illness. When a chance encounter with a former colleague throws up hints of a dark past, it becomes clear there is more to sweet Maud than meets the eye.",
        release_date: "2020-10-09",
        vote_count: 40,
        title: "Saint Maud",
        adult: false,
        backdrop_path: "/1cMiwN34P5W8NqstPWhmT8spsDb.jpg",
        id: 575776,
        genre_ids: [27, 18, 9648],
        popularity: 55.129,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Finding 'Ohana",
        poster_path: "/tTWl37oAYRXS3D5mEHmjveXXyrN.jpg",
        video: false,
        vote_average: 6.9,
        overview:
          "Two Brooklyn siblings' summer in a rural Oahu town takes an exciting turn when a journal pointing to long-lost treasure sets them on an adventure, leading them to reconnect with their Hawaiian heritage.",
        release_date: "2021-01-29",
        vote_count: 65,
        title: "Finding 'Ohana",
        adult: false,
        backdrop_path: "/yImmxRokQ48PD49ughXdpKTAsAU.jpg",
        id: 644092,
        genre_ids: [28, 12, 35, 10751],
        popularity: 463.511,
        media_type: "movie",
      },
      {
        original_language: "ja",
        poster_path: "/aiy35Evcofzl7hASZZvsFgltHTX.jpg",
        first_air_date: "2013-04-07",
        vote_average: 8.7,
        original_name: "進撃の巨人",
        origin_country: ["JP"],
        vote_count: 2706,
        name: "Attack on Titan",
        overview:
          "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
        backdrop_path: "/2b0s0iMNl9CgrCMz0VGKlMw3vZw.jpg",
        id: 1429,
        genre_ids: [16, 10765, 10768, 9648],
        popularity: 198.525,
        media_type: "tv",
      },
      {
        overview:
          "In the aftermath of the Great Plague and amidst the subsequent witch-hunts against women, a young widow grapples with the tragic death of her husband in a society completely consumed by fear and death. Because she rejects the advances of her landlord, she is falsely accused of being a witch and thrown in jail for a crime she didn’t commit. She must endure physical persecution at the hands of England’s most ruthless witch-hunter and face her own inner demons as the devil himself starts to work his way into her mind.",
        release_date: "2021-02-05",
        adult: false,
        backdrop_path: "/o1SRICUk6gTFrppdMLzJqi9TtDK.jpg",
        title: "The Reckoning",
        genre_ids: [27],
        original_language: "en",
        original_title: "The Reckoning",
        poster_path: "/7JrN8ShJpJuVDqEgKw4vA2dB0zH.jpg",
        vote_count: 0,
        video: false,
        id: 587130,
        vote_average: 0,
        popularity: 38.504,
        media_type: "movie",
      },
      {
        overview:
          "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
        release_date: "2020-12-25",
        adult: false,
        backdrop_path: "/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
        genre_ids: [10751, 16, 35, 18, 10402, 14],
        vote_count: 4490,
        original_language: "en",
        id: 508442,
        poster_path: "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
        title: "Soul",
        video: false,
        vote_average: 8.3,
        original_title: "Soul",
        popularity: 1418.638,
        media_type: "movie",
      },
      {
        backdrop_path: "/nrA1zkpgBSflSUTcQ5MGxT9A4Dk.jpg",
        genre_ids: [18, 80],
        first_air_date: "2019-11-01",
        original_language: "es",
        original_name: "Hache",
        origin_country: ["ES"],
        id: 84112,
        vote_count: 5,
        vote_average: 6.4,
        poster_path: "/yScOKZTBlug31LF89M3Dccymw5b.jpg",
        overview:
          "As Helena gains the trust and love of a dangerous heroin cartel leader in Barcelona, she develops the skills she needs to eventually seize his empire.",
        name: "Hache",
        popularity: 48.773,
        media_type: "tv",
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
];
